import 'dotenv/config'
import mongoose from 'mongoose'
import TransactionConfig from '../src/models/TransactionConfig.js'

await mongoose.connect(process.env.MONGODB_URI)

const corridors = [
  // ── LLC USD → LatAm via Vita (los que faltan) ──────────────────────────────
  {
    corridorId:          'us-br',
    legalEntity:         'LLC',
    routingScenario:     'D',
    originCountry:       'US',
    destinationCountry:  'BR',
    originCurrency:      'USD',
    destinationCurrency: 'BRL',
    payinMethod:         'owlPay',
    payoutMethod:        'vitaWallet',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        1.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.5,
    minimumAmount:       100,
    maximumAmount:       500000,
  },
  {
    corridorId:          'us-ar',
    legalEntity:         'LLC',
    routingScenario:     'D',
    originCountry:       'US',
    destinationCountry:  'AR',
    originCurrency:      'USD',
    destinationCurrency: 'ARS',
    payinMethod:         'owlPay',
    payoutMethod:        'vitaWallet',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        1.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.5,
    minimumAmount:       100,
    maximumAmount:       500000,
  },
  {
    corridorId:          'us-cl',
    legalEntity:         'LLC',
    routingScenario:     'D',
    originCountry:       'US',
    destinationCountry:  'CL',
    originCurrency:      'USD',
    destinationCurrency: 'CLP',
    payinMethod:         'owlPay',
    payoutMethod:        'vitaWallet',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        1.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.5,
    minimumAmount:       100,
    maximumAmount:       500000,
  },
  // ── LLC USD → Global via OwlPay (destinos no cubiertos por Vita) ───────────
  {
    corridorId:          'us-us',
    legalEntity:         'LLC',
    routingScenario:     'A',
    originCountry:       'US',
    destinationCountry:  'US',
    originCurrency:      'USD',
    destinationCurrency: 'USD',
    payinMethod:         'owlPay',
    payoutMethod:        'owlPay',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        0.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.25,
    minimumAmount:       500,
    maximumAmount:       500000,
  },
  {
    corridorId:          'us-eu',
    legalEntity:         'LLC',
    routingScenario:     'A',
    originCountry:       'US',
    destinationCountry:  'EU',
    originCurrency:      'USD',
    destinationCurrency: 'EUR',
    payinMethod:         'owlPay',
    payoutMethod:        'owlPay',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        0.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.25,
    minimumAmount:       500,
    maximumAmount:       500000,
  },
  {
    corridorId:          'us-cn',
    legalEntity:         'LLC',
    routingScenario:     'A',
    originCountry:       'US',
    destinationCountry:  'CN',
    originCurrency:      'USD',
    destinationCurrency: 'CNY',
    payinMethod:         'owlPay',
    payoutMethod:        'owlPay',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        0.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.25,
    minimumAmount:       500,
    maximumAmount:       500000,
  },
  {
    corridorId:          'us-ae',
    legalEntity:         'LLC',
    routingScenario:     'A',
    originCountry:       'US',
    destinationCountry:  'AE',
    originCurrency:      'USD',
    destinationCurrency: 'AED',
    payinMethod:         'owlPay',
    payoutMethod:        'owlPay',
    isActive:            true,
    payinFeePercent:     0,
    alytoCSpread:        0.5,
    fixedFee:            0,
    payoutFeeFixed:      0,
    profitRetentionPercent: 0.25,
    minimumAmount:       500,
    maximumAmount:       500000,
  },
]

for (const corridor of corridors) {
  await TransactionConfig.findOneAndUpdate(
    { corridorId: corridor.corridorId },
    { $setOnInsert: corridor },
    { upsert: true, new: true }
  )
  console.log(`✅ Corredor ${corridor.corridorId} → ${corridor.destinationCountry} (${corridor.payoutMethod})`)
}

await mongoose.disconnect()
console.log('\n✅ Seed LLC completado.')
